name: ci

on: [push, pull_request]

jobs:
  ci:
    strategy:
      matrix:
        elixir: ["1.10"]
        otp: ["22.2"]
        postgres: ["12.2-alpine"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          key: test-${{ hashFiles('mix.lock') }}
          path: _build

      - uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          experimental-otp: true

      - name: Run mix deps.get
        run: mix deps.get

      - name: Run mix compile
        env:
          MIX_ENV: test
        run: mix compile

      - name: Build tty0tty
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq linux-headers-`uname -r`
          git clone --depth=50 https://github.com/freemed/tty0tty.git
          cd tty0tty/module && make && sudo cp tty0tty.ko /lib/modules/$(uname -r)/kernel/drivers/misc/
          cd -
          sudo depmod
          sudo modprobe tty0tty
          sudo chmod 666 /dev/tnt*

      - name: Run mix test
        env:
          MIX_ENV: test
          SIM_DEVICE: /dev/tnt0
          QMI_DEVICE: /dev/tnt1
        run: mix test
